### ISSUE TITLE
Some cost-randomization effects don't work

### ISSUE THREAD

**Issue by Astralika** [gygrazok/witchmod#10]
In particular in this instance, Replay The Spire's Delirium curse, which randomizes card-costs for one turn, doesn't seem to work appropriately for the Witch. SPECIFICALLY the Witch, which was strange to me! I tested this with both another modded character and a vanilla character and it only didn't work for the witch. I know it's not exactly you guys' job to fix these interactions but since it seemed specific to Witch and not, in this example, Mad Scientist or anything else, that you'd be the ones to go to.

**Comment by gygrazok** [comment]
Should be fixed in the next release. Thanks for the report.
