### ISSUE TITLE
Mystic Unburial is only able to pick from a small subset of the playable cards

### ISSUE THREAD

**Issue by SilentJ28** [gygrazok/witchmod#13]
Cast Mystic Unburial+ and given the choice of Zombie Spit+(0 cost) and Decrepify+(X cost). It seems like it is filtering out all the cards that I don't have mana to cast (currently at 0 mana) despite Mystic Unburial being upgraded and letting me ignore cost. Lots of 1 to 3 cost cards in the discard that aren't being shown.

**Comment by SilentJ28** [comment]
Ah that is the case. When I cast Mystic Unburial+ with 1 mana available, I am shown all cards with 1 mana cost and less in addtion to X cards.

**Comment by gygrazok** [comment]
Fixed due to Mystic Unburial rework
