### ISSUE TITLE
Mystic Unburial+ pays energy cost for X cards

### ISSUE THREAD

**Issue by Daenyth** [gygrazok/witchmod#18]
I expected it to ignore the cost of the X card, similar to `Havoc`, but it depleted all my energy instead

**Comment by SilentJ28** [comment]
The reworked Mystic Unburial in the change logs simply returns the card to your hand so this should no longer be an issue

**Comment by Daenyth** [comment]
That does change how it works with X cards, but it also fits better in the game, so that's reasonable enough
