### ISSUE TITLE
MTS Version Issue

### ISSUE THREAD

**Issue by CursedFoxfire** [gygrazok/witchmod#30]
Thanks for letting me know on the update for the mod but now with the updated version it says it requires ModTheSpire v3.3.0. I've been digging for hours making sure everything is up to date but I have not found anything higher than 3.2.0 for MTS. Am I just missing it or looking in the wrong place? As of right now I can't even select the mod within the MTS launcher.

**Comment by gygrazok** [comment]
Whoops! Thanks for the report, should be fixed in the new 1.1.1 release.
