### ISSUE TITLE
Wretched Nails opening hand bugged

### ISSUE THREAD

**Issue by Eclipse-Shadow-Scale** [gygrazok/witchmod#33]
if you draw wretched nails in the first turn of combat, it deals 5 extra damage. all other turns are normal

**Comment by Eclipse-Shadow-Scale** [comment]
update: the card counts card draw from the last turn of the previous combat, as card draw on your first turn of the following combat.

**Comment by gygrazok** [comment]
Fixed in the latest release. Thanks for the report
