### ISSUE TITLE
Witch mod crash

### ISSUE THREAD

**Issue by DrBlocks** [gygrazok/witchmod#35]
For no reason I could understand (I dont know anything about java code though), Witch mod crashes
(Log window displays a few lines, screen goes black as if game was about to start, then back to the log window).
I tried to understand the crash log and find references over the web, but it's way out of my understanding.
I posted the log on pastebin since it's quite long, and took a screenshot of my ModTheSpire start panel.
If any more info is required, do ask.

I'm completely new to GitHub and feeling a bit lost; I'm sorry if my message is not at the right place or anything of that sort :/

MTS screenshot : https://i.postimg.cc/yNy16Nn5/Capture.png
MTS log : https://pastebin.com/3EYRZ9Zj

**Comment by gygrazok** [comment]
It seems like the latest patch broke the witch again!
I'll try to fix it as soon as possible. Thanks for the report

**Comment by gygrazok** [comment]
Ok should be fixed in the new release. Make sure to update basemod to the lastest version and let me know if it happens again
