### ISSUE TITLE
Choosing "Gain a curse. Transform 2 cards" crashes game

### ISSUE THREAD

**Issue by jjpdx** [gygrazok/witchmod#4]
So far I've gotten it twice and both times it crashed. Unsure if it's directly related to that option or a specific card I was transforming into (both times I picked a strike and a defend to transform)

**Comment by gygrazok** [comment]
If you manage to make it happen again, can you please paste any exceptions logged in the mod the spire console? That would be very helpful to pinpoint the error. 
Thank you

**Comment by jjpdx** [comment]
Update: This is a BaseMod bug. Closing
