### ISSUE TITLE
"Harmlessness" does nothing when played if cleansed and played on turn 1

### ISSUE THREAD

**Issue by jjpdx** [gygrazok/witchmod#6]

**Comment by jjpdx** [comment]
Update: Only happens if you had it in your starting hand.

**Comment by jjpdx** [comment]
Update: Actually happens if you cleanse it the turn it is "created." If you get one from Dead Branch and cleanse it the same turn, it also does nothing when played.

**Comment by gygrazok** [comment]
Should be fixed in the current (0.7) release. Thanks for the report

**Comment by SirHaesslich** [comment]
It did not get fixed. Yesterday I tried to play it the turn it was cleansed and it did nothing. But now it does correctly calculate damage if it actually deals it at all

**Comment by Astralika** [comment]
Happened again, though I can confirm this time it was because I'd drawn it with Wicked Thoughts.

**Comment by gygrazok** [comment]
Fixed. Thanks.
