### ISSUE TITLE
crash on start up before menu

### ISSUE THREAD

**Issue by Asger91** [gygrazok/witchmod#8]
Since the newest Update (Beta and non Beta build) the game crashes right before it gets to the menu, after the Megacrit screen.
It only happens if you have a character mod checked in the Modloader.

Here is a picture of it,

![untitled](https://user-images.githubusercontent.com/38844325/39411786-4406e768-4c11-11e8-9d32-b7d6d1268557.png)

**Comment by gygrazok** [comment]
Hi, I didn't have much time lately to work on this; I think I'll look into it as soon as the 3rd character is officially added in the game, so that I can fix it for good.
Thanks for the report.
