### ISSUE TITLE
Slight cosmetic inconsistency?

### ISSUE THREAD

**Issue by SirHaesslich** [gygrazok/witchmod#9]
When choosing which mods to enable in ModTheSpire window, your mod is highlighted yellow with commentary "this mod explicitly supports week 25 patch", despite it being updated to the latest version. The game was successfully launched. I am not sure if this is a problem from your side, but just maybe to take a quick look at it if no other issues are at hand would increase the mod's appearance of reliability.

**Comment by gygrazok** [comment]
Fixed in the latest release, thanks for the report.
(although this will probably happen again when a new patch is released)
